#!/bin/bash

CONFIGDIR=$1
CONFIG="${1}/config"

cp bashrc ${HOME}/.bashrc
cp bash_aliases ${HOME}/.bash_aliases

# Copy all files in i3/ except config
for I in `find i3/* | grep -v 'config$'`
do
	chmod +x $I
	cp $I $CONFIGDIR
done

echo "# From https://github.com/jesper3/.dotfiles " > $CONFIG

for I in copyterm openenv i3init
do
	echo "set \$${I} ${CONFIGDIR}/${I}" >> $CONFIG
done

I="0"
while [ $I -lt 10 ]
do
	echo "set \$bg${I} exec --no-startup-id feh --bg-scale ${CONFIGDIR}/bg${I}" >> $CONFIG
	I=$[$I+1]
done

cat i3/config >> $CONFIG
